baseurl = "mariaines.dk/portfolio9"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "Min Cv"


[params]
	showglobe = true

	favicon = "favicon.ico"
	
	analytics = "code-here"

	email = "mariaines@outlook.dk"

	profilepic = "img/me.jpg"
	
	title = "Maria Ines"
	subtitle = "min CV"

	
	
#Menu
	
	
	[[params.navlinks]]
	name = "forside"
    weight = 0
    identifier = "forside"
	url = "_index"
    
    [[params.navlinks]]
	name = "om"
    weight = 1
    identifier = "om"
	url = "om"
	
	[[params.navlinks]]
	name = "kontakt"
    weight = 2
    identifier = "kontakt"
	url = "kontakt"
	
	    
    [[params.navlinks]]
	name = "blog"
    weight = 3
    identifier = "blog"
	url = "blog/"
    
    [[params.navlinks]]
	name = "portfolio"
    weight = 4
    identifier = "portfolio"
	url = "portfolio/"

	
	

